version: "2"
services:
  web:
    image: wgsdg
    command: "'bin/rails s -b 0.0.0.0'"
    container_name: wgsdg-rails
    volumes:
      - $PWD/..:/usr/src/app
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  background_worker:
    image: wgsdg
    command: "'bundle exec sidekiq'"
    container_name: wgsdg-background-workers
    volumes:
      - $PWD/..:/usr/src/app
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  autotest:
    image: wgsdg
    command: "'bundle exec autotest'"
    container_name: wgsdg-autotest
    volumes:
      - $PWD/..:/usr/src/app
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      RAILS_ENV: test
  postgres:
    image: postgres:9.5
    container_name: wgsdg-postgres
    environment:
      POSTGRES_USER: wgsdg
      POSTGRES_PASSWORD: wgsdg
    expose:
      - "5432"
  redis:
    image: redis:3.0
    container_name: wgsdg-redis
