default: &default
  adapter:  postgresql
  encoding: utf8
  host:     postgres
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port:     5432
  username: wgsdg
  password: wgsdg

development:
  <<: *default
  database: wgsdg_dev

test:
  <<: *default
  database: wgsdg_test
